thedaviddias/llms-txt-hub

- .github/SECURITY.md
- apps/web/app/layout.tsx
- apps/web/app/not-found.tsx
- configs/typescript/package.json
- packages/observability/client.ts
- packages/observability/instrumentation.ts
- packages/observability/package.json
- packages/observability/providers/index.tsx
- packages/observability/user-context.ts
- pnpm-lock.yaml
This pull request includes several changes to enhance the observability and security of the application, as well as to update some references and dependencies. The most important changes are grouped below by theme.
* Added logic to set the environment and adjust sampling rates based on whether the application is in development or production. Included the environment in the initial Sentry scope.
* Introduced a new hook `useSentryUser` to automatically set the Sentry user context when the authentication state changes.
* Added a utility function `configureSentryUser` to configure Sentry user context with GitHub user information.
* Integrated the `useSentryUser` hook into the `RootLayout` component.
* Updated the GitHub Security Advisory link to point to the correct repository.
* Updated the …
> feat: add sentry improvements and user

- content/websites/better-auth.mdx
This PR adds Better Auth to the llms.txt hub.
Submitted by: @thedaviddias
Website: https://www.better-auth.com
llms.txt: https://www.better-auth.com/llms.txt
> feat: add Better Auth to llms.txt hub

- content/websites/bucket.mdx
This PR adds Bucket to the llms.txt hub.
Submitted by: @thedaviddias
Website: https://docs.bucket.co/
llms.txt: https://docs.bucket.co/llms.txt
> feat: add Bucket to llms.txt hub

- README.md
- apps/web/actions/submit-llms-xxt.ts
- apps/web/app/(legal)/privacy/page.tsx
- apps/web/app/(legal)/terms/page.tsx
- apps/web/app/about/page.tsx
- apps/web/app/faq/page.tsx
- apps/web/app/guides/[slug]/page.tsx
- apps/web/app/guides/page.tsx
- apps/web/app/layout.tsx
- apps/web/app/login/page.tsx
- apps/web/app/news/page.tsx
- apps/web/app/opengraph-image.alt.txt
- apps/web/app/page.tsx
- apps/web/app/search/page.tsx
- apps/web/app/websites/[slug]/page.tsx
- apps/web/app/websites/page.tsx
- apps/web/components/layout/footer.tsx
- apps/web/components/layout/header.tsx
- apps/web/components/search/search-results.tsx
- apps/web/components/sections/faq-section.tsx
- apps/web/components/sections/hero-section.tsx
- apps/web/components/sections/newsletter-section.tsx
- apps/web/lib/schema.ts
- content/guides/getting-started-llms-txt.mdx
- content/legal/privacy.mdx
- content/legal/terms.mdx
> feat: add seo json ld

- content/websites/openrouter.mdx
This PR adds OpenRouter to the llms.txt hub.
Submitted by: @alexanderatallah
Website: https://openrouter.ai/
llms.txt: https://openrouter.ai/docs/llms.txt
llms-full.txt: https://openrouter.ai/docs/llms-full.txt
> feat: add OpenRouter to llms.txt hub

- content/websites/demo-time.mdx
This PR adds Demo Time to the llms.txt hub.
Submitted by: @estruyf
Website: https://demotime.elio.dev
llms.txt: https://demotime.elio.dev/llms.txt
> feat: add Demo Time to llms.txt hub

- content/websites/front-matter-cms---a-cms-in-your-vs-code-editor.mdx
This PR adds Front Matter CMS - a CMS in your VS Code editor to the llms.txt hub.
Submitted by: @estruyf
Website: https://frontmatter.codes
llms.txt: https://frontmatter.codes/llms.txt
> feat: add Front Matter CMS - a CMS in your VS Code editor to llms.txt hub

- content/websites/bun-—-a-fast-all.mdx
This PR adds Bun — A fast all to the llms.txt hub.
Submitted by: @Anulo2
Website: https://bun.sh
llms.txt: https://bun.sh/llms.txt
> feat: add Bun — A fast all to llms.txt hub

- content/websites/glama.mdx
This PR adds All to the llms.txt hub.
Submitted by: @thedaviddias
Website: https://glama.ai
llms.txt: https://glama.ai/llms.txt
> feat: add All to llms.txt hub

- content/websites/netlify.mdx
This PR adds Netlify to the llms.txt hub.
Submitted by: @sean-roberts
Website: https://docs.netlify.com
llms.txt: https://docs.netlify.com/llms.txt
> feat: add Netlify to llms.txt hub

- content/websites/creative-handbook-production-resource-directory.mdx
This PR adds Creative Handbook Production Resource Directory to the llms.txt hub.
Submitted by: @Daggerdru
Website: https://www.creativehandbook.com
llms.txt: https://www.creativehandbook.com/llms.txt
> feat: add Creative Handbook Production Resource Directory to llms.txt hub

- content/websites/simplepdf.mdx
This PR adds SimplePDF to the llms.txt hub.
Submitted by: @bendersej
Website: https://simplepdf.com/llms.txt
llms.txt: https://simplepdf.com/llms.txt
> feat: add SimplePDF to llms.txt hub

- README.md
This PR updates the llms.txt list in README.md based on the current state of llms.txt in the repository.
- Updates completion status of patterns
- Adds new llms.txt
- Updates links to completed llms.txt
> docs: update llms.txt list

- apps/web/lib/content-loader.ts
This pull request focuses on improving the robustness and clarity of the content loading process in the `apps/web/lib/content-loader.ts` file. The key changes include safer path resolution for base directories, enhanced fallback mechanisms for loading JSON files, and additional logging for better debugging.
Improvements to path resolution and fallback mechanisms:
* Replaced direct path concatenation with the `resolveFromRoot` utility function for safer path resolution of the `contentBase` and `dataDir` directories.
* Enhanced the `loadWebsites` function to try multiple possible locations for the `websites.json` file, improving the fallback mechanism when the primary directory is not found.
Additional logging for debugging:
* Added logging statements to output the current working …
> fix: trying to resolve wrong path vercel

- content/websites/vue-macros.mdx
This PR adds Vue Macros to the llms.txt hub.
Submitted by: @sxzz
Website: https://vue-macros.dev/
llms.txt: https://vue-macros.dev/llms.txt
llms-full.txt: https://vue-macros.dev/llms-full.txt
> feat: add Vue Macros to llms.txt hub

- .gitignore
- apps/web/app/.well-known/vercel/flags/route.ts
- apps/web/package.json
- packages/flags/access.ts
- packages/flags/components/toolbar.tsx
- packages/flags/index.ts
- packages/flags/keys.ts
- packages/flags/lib/create-flag.ts
- packages/flags/lib/toolbar.ts
- packages/flags/package.json
- packages/flags/tsconfig.json
- pnpm-lock.yaml
> feat: add flags package

- apps/web/components/forms/submit-form.tsx
This pull request includes several changes to the `apps/web/components/forms/submit-form.tsx` file to improve validation and processing of form inputs. The most important changes include refining URL validation, adjusting character limits for names, and trimming whitespace from names before submission.
Validation improvements:
* Enhanced URL validation to ensure the website URL does not include 'llms.txt'.
* Adjusted the maximum character limit for names from 50 to 40 for optimal display and SEO.
Input processing:
* Added preprocessing to trim whitespace from names before adding them to the form data.
> refactor: improve title and website

- content/websites/best-boat-lifts.mdx
This PR adds Best Boat Lifts to the llms.txt hub.
Submitted by: @NVGONE
Website: https://iqboatlifts.com/
llms.txt: https://iqboatlifts.com/llms.txt
llms-full.txt: https://iqboatlifts.com/llms-full.txt
> feat: add Best Boat Lifts to llms.txt hub

- content/websites/postfast.mdx
This PR adds PostFast to the llms.txt hub.
Submitted by: @peturgeorgievv
Website: https://postfa.st
llms.txt: https://postfa.st/llms.txt
llms-full.txt: https://postfa.st/llms-full.txt
> feat: add PostFast to llms.txt hub

- content/websites/semgrep.mdx
This PR adds Semgrep to the llms.txt hub.
Submitted by: @DrewDennison
Website: https://semgrep.com
llms.txt: https://semgrep.com/llms.txt
llms-full.txt: https://semgrep.com/llms-full.txt
Category: security-identity
> feat: add Semgrep to llms.txt hub

- content/websites/lm-studio.mdx
This PR adds LM Studio to the llms.txt hub.
Submitted by: @Vincentkhc
Website: https://lmstudio.ai/
llms.txt: https://lmstudio.ai/llms.txt
llms-full.txt: https://lmstudio.ai/llms-full.txt
> feat: add LM Studio to llms.txt hub

- content/websites/trackvia.mdx
This PR adds TrackVia to the llms.txt hub.
Submitted by: @JacobHartmannTrackVia
Website: https://trackvia.com
llms.txt: https://trackvia.com/llms.txt
> feat: add TrackVia to llms.txt hub

- packages/content/data/websites/promptfoo-llms-txt.mdx
Add promptfoo to llms.txt directory - An open-source platform for evaluating, testing, and red-teaming LLM applications. promptfoo helps developers build more reliable AI applications through comprehensive testing methodologies. Website: https://www.promptfoo.dev
> Add promptfoo - LLM testing and evaluation platform

- content/websites/docker-docs-llms-txt.mdx
This PR adds Docker Docs to the llms.txt hub.
Submitted by: @daringcalf
Website: https://docs.docker.com
llms.txt: https://docs.docker.com/llms.txt
> feat: add Docker Docs to llms.txt hub

- content/websites/expo-documentation-llms-txt.mdx
This PR adds Expo Documentation to the llms.txt hub.
Submitted by: @YoanAncelly
Website: https://docs.expo.dev
llms.txt: https://docs.expo.dev/llms.txt
llms-full.txt: https://docs.expo.dev/llms-full.txt
> feat: add Expo Documentation to llms.txt hub

- content/websites/tamagui-llms-txt.mdx
This PR adds Tamagui to the llms.txt hub.
Submitted by: @YoanAncelly
Website: https://tamagui.dev
llms.txt: https://tamagui.dev/llms.txt
> feat: add Tamagui to llms.txt hub

- content/websites/pydantic-llms-txt.mdx
This PR adds Pydantic to the llms.txt hub.
Submitted by: @YoanAncelly
Website: https://docs.pydantic.dev/latest/
llms.txt: https://docs.pydantic.dev/latest/llms.txt
llms-full.txt: https://docs.pydantic.dev/latest/llms-full.txt
> feat: add Pydantic to llms.txt hub

- content/websites/giselle-llms-txt.mdx
This PR adds Giselle to the llms.txt hub.
Submitted by: @masutaka
Website: https://giselles.ai/
llms.txt: https://docs.giselles.ai/llms.txt
llms-full.txt: https://docs.giselles.ai/llms-full.txt
> feat: add Giselle to llms.txt hub

- content/websites/prettier-llms-txt.mdx
This PR adds Prettier to the llms.txt hub.
Submitted by: @fisker
Website: https://prettier.io/
llms.txt: https://prettier.io/llms.txt
llms-full.txt: https://prettier.io/llms-full.txt
> Add Prettier to llms.txt directory

- content/websites/uniwebview-llms-txt.mdx
This PR adds UniWebView to the llms.txt hub.
Submitted by: @onevcat
Website: https://docs.uniwebview.com
llms.txt: https://docs.uniwebview.com/llms.txt
llms-full.txt: https://docs.uniwebview.com/llms-full.txt
> feat: add UniWebView to llms.txt hub

- content/websites/salesforce-marketing-cloud-consultants-llms-txt.mdx
This PR adds Salesforce Marketing Cloud Consultants to the llms.txt hub.
Submitted by: @TomRyanPardot
Website: https://marcloudconsulting.com/
llms.txt: https://marcloudconsulting.com/llms.txt
llms-full.txt: https://marcloudconsulting.com/llms-full.txt
> feat: add Salesforce Marketing Cloud Consultants to llms.txt hub

- content/websites/trueprofit-llms-txt.mdx
This PR adds TrueProfit to the llms.txt hub.
Submitted by: @datnpfiregroup
Website: https://trueprofit.io/
llms.txt: https://trueprofit.io/llms.txt
> feat: add TrueProfit to llms.txt hub

- content/websites/loglayer---a-logger-for-typescript-llms-txt.mdx
This PR adds LogLayer - A logger for Typescript to the llms.txt hub.
Submitted by: @theogravity
Website: https://loglayer.dev
llms.txt: https://loglayer.dev/llms.txt
llms-full.txt: https://loglayer.dev/llms-full.txt
> feat: add LogLayer - A logger for Typescript to llms.txt hub

- packages/content/websites/data/nativescript-llms-txt.mdx
This PR adds Nativescript to the llms.txt hub.
Submitted by: @mleleux-heykiddo
Website: https://docs.nativescript.org
llms.txt: https://docs.nativescript.org/llms.txt
llms-full.txt: https://docs.nativescript.org/llms-full.txt
> feat: add Nativescript to llms.txt hub

- packages/content/websites/data/lettermint-llms-txt.mdx
This PR adds Lettermint to the llms.txt hub.
Submitted by: @Bjornftw
Website: https://lettermint.co
llms.txt: https://lettermint.co/llms.txt
> feat: add Lettermint to llms.txt hub

- packages/content/websites/data/film-and-screenwriter-school-llms-txt.mdx
This PR adds Film and Screenwriter School to the llms.txt hub.
Submitted by: @toolroom75
Website: https://www.filmconnection.com/ 
llms.txt: https://www.filmconnection.com/llms.txt
llms-full.txt: https://www.filmconnection.com/llms-full.txt
> feat: add Film and Screenwriter School to llms.txt hub

- packages/content/websites/data/swipe,-simple-invoicing-and-payments-app-llms-txt.mdx
This PR adds Swipe, Simple Invoicing and Payments app to the llms.txt hub.
Submitted by: @swipe9
Website: https://getswipe.in/
llms.txt: https://getswipe.in/llms.txt
> feat: add Swipe, Simple Invoicing and Payments app to llms.txt hub

- packages/content/websites/data/ai-sdk-llms-txt.mdx
This PR adds AI SDK to the llms.txt hub.
Submitted by: @Louis454545
Website: https://ai-sdk.dev/
llms.txt: https://ai-sdk.dev/llms.txt
> feat: add AI SDK to llms.txt hub

- packages/content/websites/data/lobehub-llms-txt.mdx
This PR adds LobeHub to the llms.txt hub.
Submitted by: @canisminor1990
Website: https://lobehub.com
llms.txt: https://lobehub.com/llms.txt
llms-full.txt: https://lobehub.com/llms-full.txt
> feat: add LobeHub to llms.txt hub

- packages/content/websites/data/best-app-development-company-llms-txt.mdx
This PR adds Best App Development Company to the llms.txt hub.
Submitted by: @deepakkr-dm
Website: https://quokkalabs.com/
llms.txt: https://quokkalabs.com/llms.txt
> feat: add Best App Development Company to llms.txt hub

- packages/content/websites/data/mixo-llms-txt.mdx
> Add Mixo to llms-txt directory

- packages/content/websites/data/domain-marketplace-llms-txt.mdx
This PR adds Domain Marketplace to the llms.txt hub.
Submitted by: @namegulf
Website: https://namegulf.com
llms.txt: https://namegulf.com/llms.txt
llms-full.txt: https://namegulf.com/llms-full.txt
> feat: add Domain Marketplace to llms.txt hub

- packages/content/websites/data/document-file-translation-powered-by-ai-llms-txt.mdx
This PR adds Document File Translation Powered by AI to the llms.txt hub.
Submitted by: @xyt0102
Website: https://doc2lang.com
llms.txt: https://doc2lang.com/llms.txt
> feat: add Document File Translation Powered by AI to llms.txt hub

- packages/content/websites/data/statusfield-llms-txt.mdx
This PR adds Statusfield to the llms.txt hub.
Submitted by: @javiergarzac
Website: https://statusfield.com
llms.txt: https://statusfield.com/llms.txt
> feat: add Statusfield to llms.txt hub

- packages/content/websites/data/aceessay.ai-llms-txt.mdx
This PR adds AceEssay.ai to the llms.txt hub.
Submitted by: @RedisOptional
Website: https://aceessay.ai/
llms.txt: https://aceessay.ai/llms.txt
llms-full.txt: https://aceessay.ai/llms-full.txt
> feat: add AceEssay.ai to llms.txt hub

- packages/content/websites/data/id21-llms-txt.mdx
This PR adds ID21 to the llms.txt hub.
Website: https://id21.com.sg/
llms.txt: https://id21.com.sg/llms.txt
llms-full.txt: https://id21.com.sg/llms-full.txt
> feat: add ID21 to llms.txt hub

- packages/content/websites/data/abogado-online-y-asesoría-legal-llms-txt.mdx
This PR adds Abogado online y asesoría legal to the llms.txt hub.
Submitted by: @AbogadoExpres
Website: https://abogadoexpres.es/
llms.txt: https://abogadoexpres.es/llms.txt
Category: security-identity
> feat: add Abogado online y asesoría legal to llms.txt hub

- packages/content/websites/data/rapidtextai-llms-txt.mdx
This PR adds RapidTextAI to the llms.txt hub.
Submitted by: @alisaleem252
Website: https://app.rapidtextai.com/
llms.txt: https://app.rapidtextai.com/llms.txt
llms-full.txt: https://app.rapidtextai.com/llms-full.txt
> feat: add RapidTextAI to llms.txt hub

- packages/content/websites/data/vignette-id-llms-txt.mdx
This PR adds Vignette ID to the llms.txt hub.
Submitted by: @pawlek
Website: https://e-vignettes.eu
llms.txt: https://e-vignettes.eu/llms.txt
llms-full.txt: https://e-vignettes.eu/llms-full.txt
> feat: add Vignette ID to llms.txt hub

- packages/content/websites/data/nextevogroup-llms-txt.mdx
This PR adds NextevoGroup to the llms.txt hub.
Website: https://nextevogroup.com/
llms.txt: https://nextevogroup.com/llms.txt
llms-full.txt: https://nextevogroup.com/llms-full.txt
> feat: add NextevoGroup to llms.txt hub

- packages/content/websites/data/nextevo-llms-txt.mdx
This PR adds Nextevo to the llms.txt hub.
Website: https://nextevo.one/
llms.txt: https://nextevo.one/llms.txt
llms-full.txt: https://nextevo.one/llms-full.txt
> feat: add Nextevo to llms.txt hub

- packages/content/websites/data/ufc-velvet-llms-txt.mdx
This PR adds UFC Velvet to the llms.txt hub.
Website: https://ufcvelvet.com/
llms.txt: https://ufcvelvet.com/llms.txt
llms-full.txt: https://ufcvelvet.com/llms-full.txt
> feat: add UFC Velvet to llms.txt hub

- packages/content/websites/data/plan-harmony-|-travel-planning-llms-txt.mdx
This PR adds Plan Harmony | Travel Planning to the llms.txt hub.
Submitted by: @mikeluby
Website: https://planharmony.com/
llms.txt: https://planharmony.com/llms.txt
llms-full.txt: https://planharmony.com/llms-full.txt
> feat: add Plan Harmony | Travel Planning to llms.txt hub

- packages/content/websites/data/wf-content-creator-platform-llms-txt.mdx
This PR adds WF Content Creator Platform to the llms.txt hub.
Website: https://kol.wunderfauks.com/
llms.txt: https://kol.wunderfauks.com/llms.txt
llms-full.txt: https://kol.wunderfauks.com/llms-full.txt
> feat: add WF Content Creator Platform to llms.txt hub

- packages/content/websites/data/geförderte-online-weiterbildung-llms-txt.mdx
This PR adds Geförderte Online Weiterbildung to the llms.txt hub.
Submitted by: @drexlma
Website: https://www.dbe.academy/
llms.txt: https://www.dbe.academy/llms.txt
llms-full.txt: https://www.dbe.academy/llms-full.txt
> feat: add Geförderte Online Weiterbildung to llms.txt hub

- packages/content/websites/data/television.ai-llms-txt.mdx
This PR adds Television.AI to the llms.txt hub.
Submitted by: @olcaybuyan
Website: https://www.television.ai/
llms.txt: https://www.television.ai/llms.txt
> feat: add Television.AI to llms.txt hub

- packages/content/websites/data/heritage-collection-llms-txt.mdx
This PR adds Heritage Collection to the llms.txt hub.
Website: https://hericoll.com
llms.txt: https://hericoll.com/llms.txt
llms-full.txt: https://hericoll.com/llms-full.txt
> feat: add Heritage Collection to llms.txt hub

- packages/content/websites/data/voyager-shuffle-llms-txt.mdx
This PR adds Voyager Shuffle to the llms.txt hub.
Website: https://games.stardreamcruises.com/
llms.txt: https://games.stardreamcruises.com/llms.txt
> feat: add Voyager Shuffle to llms.txt hub

- packages/content/websites/data/najboljši-online-casino-slovenija-2025-llms-txt.mdx
This PR adds Najboljši Online Casino Slovenija 2025 to the llms.txt hub.
Submitted by: @djouni1
Website: https://slovenija-casino.com/
llms.txt: https://slovenija-casino.com/llms.txt
> feat: add Najboljši Online Casino Slovenija 2025 to llms.txt hub

- packages/content/websites/data/flows-llms-txt.mdx
This PR adds Flows to the llms.txt hub.
Submitted by: @OPesicka
Website: https://flows.sh/
llms.txt: https://flows.sh/llms.txt
> feat: add Flows to llms.txt hub

- packages/content/websites/data/contractor-marketing-agency-llms-txt.mdx
This PR adds Contractor Marketing Agency to the llms.txt hub.
Submitted by: @cgn-support
Website: https://contractorgrowthnetwork.com/
llms.txt: https://contractorgrowthnetwork.com/llms.txt
> feat: add Contractor Marketing Agency to llms.txt hub

- packages/content/websites/data/cdata-software-llms-txt.mdx
This PR adds CData Software to the llms.txt hub.
Submitted by: @jerodj-cdata
Website: https://www.cdata.com
llms.txt: https://www.cdata.com/llms.txt
> feat: add CData Software to llms.txt hub

- packages/content/websites/data/leather-jackets,-coats-for-men-&-women-llms-txt.mdx
This PR adds Leather Jackets, Coats For Men & Women to the llms.txt hub.
Submitted by: @HammadEsire
Website: https://www.angeljackets.com/ca
llms.txt: https://www.angeljackets.com/ca/llms.txt
> feat: add Leather Jackets, Coats For Men & Women to llms.txt hub

- packages/content/websites/data/film-and-screenwriting-school-llms-txt.mdx
This PR adds Film and Screenwriting School to the llms.txt hub.
Submitted by: @toolroom75
Website: https://www.filmconnection.com/
llms.txt: https://www.filmconnection.com/llms.txt
llms-full.txt: https://www.filmconnection.com/llms-full.txt
> feat: add Film and Screenwriting School to llms.txt hub

- packages/content/websites/data/useapi.net-llms-txt.mdx
This PR adds useapi.net to the llms.txt hub.
Submitted by: @useapi
Website: https://useapi.net
llms.txt: https://useapi.net/llms.txt
> feat: add useapi.net to llms.txt hub

- packages/content/websites/data/ki-blog-österreich-llms-txt.mdx
This PR adds KI Blog Österreich to the llms.txt hub.
Submitted by: @7H3-CH053N
Website: https://digitalhandwerk.rocks/
llms.txt: https://digitalhandwerk.rocks/llms.txt
> feat: add KI Blog Österreich to llms.txt hub

- packages/content/websites/data/yaml-resume-llms-txt.mdx
Add [YAMLResume](https://yamlresume.dev).
Preview:
> add YAMLResume

- packages/content/websites/data/fantasy-sports-app-development-company-llms-txt.mdx
This PR adds Fantasy Sports App Development Company to the llms.txt hub.
Submitted by: @Anshul425
Website: https://www.vinfotech.com/
llms.txt: https://www.vinfotech.com/llms.txt
> feat: add Fantasy Sports App Development Company to llms.txt hub

- packages/content/websites/data/databuddy-analytics-llms-txt.mdx
This PR adds Databuddy Analytics to the llms.txt hub.
Submitted by: @izadoesdev
Website: https://www.databuddy.cc
llms.txt: https://www.databuddy.cc/llms.txt
> feat: add Databuddy Analytics to llms.txt hub

- packages/content/websites/data/payrollrabbit-llms-txt.mdx
This PR adds PayrollRabbit to the llms.txt hub.
Submitted by: @freddsomm
Website: https://www.payrollrabbit.com
llms.txt: https://www.payrollrabbit.com/llms.txt
> feat: add PayrollRabbit to llms.txt hub

- packages/content/websites/data/退職あんしん代行-|-ai×弁護士監修で2,980円-llms-txt.mdx
This PR adds 退職あんしん代行 | AI×弁護士監修で2,980円 to the llms.txt hub.
Submitted by: @nandstech01
Website: https://taishoku-anshin-daiko.com
llms.txt: https://taishoku-anshin-daiko.com/llms.txt
llms-full.txt: https://taishoku-anshin-daiko.com/llms-full.txt
> feat: add 退職あんしん代行 | AI×弁護士監修で2,980円 to llms.txt hub

- packages/content/websites/data/callback-technologies-llms-txt.mdx
This PR adds Callback Technologies to the llms.txt hub.
Submitted by: @matts-nsoftware
Website: https://www.callback.com/
llms.txt: https://www.callback.com/llms.txt
> feat: add Callback Technologies to llms.txt hub

- packages/content/websites/data/kruzty-llms-txt.mdx
This PR adds Kruzty to the llms.txt hub.
Submitted by: @Ishu1998
Website: https://www.kruzty.com
llms.txt: https://www.kruzty.com/llms.txt
> feat: add Kruzty to llms.txt hub

- packages/content/websites/data/twicpics-by-frontify-llms-txt.mdx
This PR adds TwicPics by Frontify to the llms.txt hub.
Submitted by: @florentb
Website: https://www.twicpics.com
llms.txt: https://www.twicpics.com/llms.txt
> feat: add TwicPics by Frontify to llms.txt hub

- packages/content/websites/data/home---tz-llms-txt.mdx
This PR adds Home - TZ to the llms.txt hub.
Submitted by: @Peter1234-debug
Website: https://tz-machinery.com
llms.txt: https://tz-machinery.com/llms.txt
> feat: add Home - TZ to llms.txt hub

- packages/content/websites/data/rims,-tires-for-cars-and-trucks-llms-txt.mdx
This PR adds Rims, Tires for Cars and Trucks to the llms.txt hub.
Submitted by: @githdean22222
Website: https://www.performanceplustire.com/
llms.txt: https://www.performanceplustire.com/llms.txt
llms-full.txt: https://www.performanceplustire.com/llms-full.txt
> feat: add Rims, Tires for Cars and Trucks to llms.txt hub

- packages/content/websites/data/lunacy-llms-txt.mdx
This PR adds Lunacy to the llms.txt hub.
Submitted by: @uksla
Website: https://icons8.com/lunacy
llms.txt: https://lunacy.docs.icons8.com/llms.txt
llms-full.txt: https://lunacy.docs.icons8.com/llms-full.txt
> feat: add Lunacy to llms.txt hub

- packages/content/websites/data/mekalite-cnc-machining-services-llms-txt.mdx
This PR adds Mekalite CNC Machining Services to the llms.txt hub.
Submitted by: @kaiyunsptos
Website: https://cncmekalite.com/
llms.txt: https://cncmekalite.com/llms.txt
> feat: add Mekalite CNC Machining Services to llms.txt hub

- packages/content/websites/data/concept-designs-&-marketing-llms-txt.mdx
This PR adds Concept Designs & Marketing to the llms.txt hub.
Submitted by: @Wineerasheed
Website: https://www.concept-designs.com.au/
llms.txt: https://www.concept-designs.com.au/llms.txt
llms-full.txt: https://www.concept-designs.com.au/llms-full.txt
> feat: add Concept Designs & Marketing to llms.txt hub

- packages/content/websites/data/aureus-erp-llms-txt.mdx
This PR adds Aureus ERP to the llms.txt hub.
Submitted by: @anikeshwebkul
Website: https://aureuserp.com/
llms.txt: https://aureuserp.com/llms.txt
> feat: add Aureus ERP to llms.txt hub

- packages/content/websites/data/embed-notion-pages-into-your-website-llms-txt.mdx
This PR adds Embed Notion Pages Into Your Website to the llms.txt hub.
Submitted by: @lepaulb
Website: https://embednotionpages.com/
llms.txt: https://embednotionpages.com/llms.txt
> feat: add Embed Notion Pages Into Your Website to llms.txt hub

- packages/content/websites/data/retainful-llms-txt.mdx
This PR adds Retainful to the llms.txt hub.
Submitted by: @YEGAPPAN-S
Website: https://www.retainful.com/
llms.txt: https://www.retainful.com/llms.txt
> feat: add Retainful to llms.txt hub

- packages/content/websites/data/sociality.io-llms-txt.mdx
This PR adds Sociality.io to the llms.txt hub.
Submitted by: @toprakkaya
Website: https://sociality.io/
llms.txt: https://sociality.io/llms.txt
> feat: add Sociality.io to llms.txt hub

- packages/content/websites/data/personal-page-llms-txt.mdx
This PR adds Personal Page to the llms.txt hub.
Submitted by: @mk230580
Website: https://pixonstudio.com/
llms.txt: https://pixonstudio.com/llms.txt
> feat: add Personal Page to llms.txt hub

- packages/content/websites/data/ruleta-aleatoria-online-gratis-llms-txt.mdx
This PR adds Ruleta aleatoria online gratis to the llms.txt hub.
Submitted by: @horushe93
Website: https://ruletaa.net/
llms.txt: https://ruletaa.net/llms.txt
llms-full.txt: https://ruletaa.net/llms-full.txt
> feat: add Ruleta aleatoria online gratis to llms.txt hub

- packages/content/websites/data/underrun.io-llms-txt.mdx
This PR adds underrun.io to the llms.txt hub.
Submitted by: @fisehara
Website: https://underrun.io
llms.txt: https://underrun.io/llms.txt
> feat: add underrun.io to llms.txt hub

- packages/content/websites/data/wot-ui-llms-txt.mdx
This PR adds Wot UI to the llms.txt hub.
Submitted by: @Moonofweisheng
Website: https://wot-design-uni.cn
llms.txt: https://wot-design-uni.cn/llms.txt
llms-full.txt: https://wot-design-uni.cn/llms-full.txt
> feat: add Wot UI to llms.txt hub

- packages/content/websites/data/短剧演员集中营微信公众号-llms-txt.mdx
This PR adds 短剧演员集中营微信公众号 to the llms.txt hub.
Submitted by: @Rayray881188
Website: https://dj.110visa.com
llms.txt: https://dj.110visa.com/llms.txt
> feat: add 短剧演员集中营微信公众号 to llms.txt hub

- packages/content/websites/data/ant-design-llms-txt.mdx
This PR adds Ant Design to the llms.txt hub.
Submitted by: @afc163
Website: https://ant.design
llms.txt: https://ant.design/llms.txt
llms-full.txt: https://ant.design/llms-full.txt
> feat: add Ant Design to llms.txt hub

- packages/content/websites/data/welcome-to-bunny-llms-txt.mdx
This PR adds Welcome to Bunny to the llms.txt hub.
Submitted by: @bunny-rich
Website: https://docs.bunny.com
llms.txt: https://docs.bunny.com/llms.txt
> feat: add Welcome to Bunny to llms.txt hub

- packages/content/websites/data/bunny-llms-txt.mdx
This PR adds Bunny to the llms.txt hub.
Submitted by: @bunny-rich
Website: https://bunny.com
llms.txt: https://bunny.com/llms.txt
> feat: add Bunny to llms.txt hub

- packages/content/websites/data/seo-kaos-llms-txt.mdx
This PR adds SEO KAOS to the llms.txt hub.
Submitted by: @seokaoscom
Website: https://www.seokaos.com/
llms.txt: https://www.seokaos.com/llms.txt
> feat: add SEO KAOS to llms.txt hub

- packages/content/websites/data/liam-erd-llms-txt.mdx
This PR adds Liam ERD to the llms.txt hub.
Submitted by: @masutaka
Website: https://liambx.com/
llms.txt: https://liambx.com/docs/llms.txt
llms-full.txt: https://liambx.com/docs/llms-full.txt
> feat: add Liam ERD to llms.txt hub

- content/websites/yellowlime-llms-txt.mdx
This PR adds Yellowlime to the llms.txt hub.
Submitted by: @YellowlimeNL
Website: https://www.yellowlime.nl/
llms.txt: https://www.yellowlime.nl/llms.txt
> feat: add Yellowlime to llms.txt hub

- content/websites/petite-box-llms-txt.mdx
This PR adds Petite Box to the llms.txt hub.
Submitted by: @gymvideo2
Website: https://www.petitebox.it
llms.txt: https://www.petitebox.it/llms.txt
> feat: add Petite Box to llms.txt hub

- content/websites/pentesting-&-red-teaming-company-llms-txt.mdx
This PR adds Pentesting & Red Teaming Company to the llms.txt hub.
Submitted by: @ayushverma79
Website: https://www.appsecure.security/
llms.txt: https://www.appsecure.security/llms.txt
llms-full.txt: https://www.appsecure.security/llms-full.txt
Category: security-identity
> feat: add Pentesting & Red Teaming Company to llms.txt hub

- content/websites/home.mdx
This PR adds Home to the llms.txt hub.
Submitted by: @coreindustries
Website: https://mondorobot.com
llms.txt: https://mondorobot.com/llms.txt
llms-full.txt: https://mondorobot.com/llms-full.txt
> feat: add Home to llms.txt hub
